# Generated by Django 4.2.27 on 2026-01-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit_logs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
