# Generated by Django 6.0.1 on 2026-01-11 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('clinic_type', models.CharField(choices=[('general_practice', 'General Practice'), ('pediatrics', 'Pediatrics'), ('dental', 'Dental'), ('eye', 'Eye Clinic'), ('womens_health', 'Women’s Health'), ('dermatology', 'Dermatology'), ('mental_health', 'Mental Health'), ('physiotherapy', 'Physiotherapy'), ('orthopedic', 'Orthopedic'), ('cardiology', 'Cardiology'), ('ent', 'ENT'), ('urology', 'Urology'), ('oncology', 'Oncology'), ('allergy', 'Allergy & Immunology'), ('pain', 'Pain Management'), ('gastroenterology', 'Gastroenterology'), ('endocrinology', 'Endocrinology'), ('neurology', 'Neurology'), ('surgical', 'Surgical Specialty'), ('urgent_care', 'Urgent Care'), ('multi_specialty', 'Multi-specialty'), ('telemedicine', 'Telemedicine'), ('community_health', 'Community Health'), ('fertility', 'Fertility & Reproductive Health'), ('geriatric', 'Geriatric')], max_length=32)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('from_clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_sent', to='referrals.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('referred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to='referrals.clinic')),
            ],
        ),
    ]
