# Generated by Django 4.2.27 on 2026-01-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("referrals", "0002_referral_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
