# Celery beat schedule for free trial expiry notifications
import os
from pathlib import Path
<<<<<<< HEAD
<<<<<<< HEAD

import dj_database_url
from celery.schedules import crontab
from dotenv import load_dotenv
from datetime import timedelta

CELERY_BEAT_SCHEDULE = {
    "send-weekly-trial-expiry-notifications": {
        "task": "billing.tasks.weekly_trial_expiry_notifications",
        "schedule": crontab(minute=0, hour=9, day_of_week="monday"),
    },
    "daily-trial-reminders": {
        "task": "billing.tasks.daily_trial_expiry_soft_reminder",
        "schedule": crontab(minute=15, hour=8),  # 08:15 UTC daily
    },
    "nightly-subscription-health-check": {
        "task": "billing.tasks.nightly_subscription_health_check",
        "schedule": crontab(minute=45, hour=1),  # 01:45 UTC daily
=======
from dotenv import load_dotenv
from celery.schedules import crontab
=======

>>>>>>> 11b5166 (Major feature updates: pagination, live search, admin dashboard, and bug fixes)
import dj_database_url
from celery.schedules import crontab
from dotenv import load_dotenv

CELERY_BEAT_SCHEDULE = {
    "send-weekly-trial-expiry-notifications": {
        "task": "billing.tasks.weekly_trial_expiry_notifications",
        "schedule": crontab(minute=0, hour=9, day_of_week="monday"),
    },
    "daily-trial-reminders": {
        "task": "billing.tasks.daily_trial_expiry_soft_reminder",
        "schedule": crontab(minute=15, hour=8),  # 08:15 UTC daily
    },
<<<<<<< HEAD
    'nightly-subscription-health-check': {
        'task': 'billing.tasks.nightly_subscription_health_check',
        'schedule': crontab(minute=45, hour=1),  # 01:45 UTC daily
>>>>>>> 453538e (Configure for Heroku deployment with PostgreSQL, Redis, and WhiteNoise)
=======
    "nightly-subscription-health-check": {
        "task": "billing.tasks.nightly_subscription_health_check",
        "schedule": crontab(minute=45, hour=1),  # 01:45 UTC daily
>>>>>>> 11b5166 (Major feature updates: pagination, live search, admin dashboard, and bug fixes)
    },
}

# Celery broker/result backend (use Redis or other broker in production)
<<<<<<< HEAD
# Handle Heroku Redis with SSL (rediss://) by disabling SSL verification
_redis_url = os.environ.get("REDIS_URL", "redis://localhost:6379/0")
_broker_url = os.environ.get("CELERY_BROKER_URL") or _redis_url
_result_url = os.environ.get("CELERY_RESULT_BACKEND") or _redis_url

# Heroku Redis uses rediss:// (SSL), convert to redis:// for local dev
# For production Heroku Redis, add SSL parameters if using rediss://
if _broker_url.startswith("rediss://"):
    # Use rediss protocol with SSL parameters for Celery
    _broker_url = _broker_url + "?ssl_cert_reqs=CERT_NONE&ssl_check_hostname=False"
if _result_url.startswith("rediss://"):
    _result_url = _result_url + "?ssl_cert_reqs=CERT_NONE&ssl_check_hostname=False"

CELERY_BROKER_URL = _broker_url
CELERY_RESULT_BACKEND = _result_url

# Celery config for production
CELERY_BROKER_USE_SSL = (
    {"keyfile": None, "certfile": None, "ca_certs": None, "cert_reqs": "CERT_NONE"}
    if _broker_url.startswith("rediss://")
    else None
)

CELERY_RESULT_BACKEND_USE_SSL = CELERY_BROKER_USE_SSL

# Email backend configuration
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
<<<<<<< HEAD
=======
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL") or os.environ.get("REDIS_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND") or os.environ.get("REDIS_URL", "redis://localhost:6379/0")

# Email backend configuration
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
>>>>>>> 453538e (Configure for Heroku deployment with PostgreSQL, Redis, and WhiteNoise)
=======
>>>>>>> 11b5166 (Major feature updates: pagination, live search, admin dashboard, and bug fixes)
# For production, use SMTP:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.example.com')
# EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
# EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'user@example.com')
# EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'password')
# EMAIL_USE_TLS = True
# DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'webmaster@example.com')
# Use custom tenant-aware authentication backend
AUTHENTICATION_BACKENDS = [
<<<<<<< HEAD
<<<<<<< HEAD
    "users.auth_backend.TenantAwareAuthBackend",
    "django.contrib.auth.backends.ModelBackend",
=======
    'users.auth_backend.TenantAwareAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
>>>>>>> 453538e (Configure for Heroku deployment with PostgreSQL, Redis, and WhiteNoise)
=======
    "users.auth_backend.TenantAwareAuthBackend",
    "django.contrib.auth.backends.ModelBackend",
>>>>>>> 11b5166 (Major feature updates: pagination, live search, admin dashboard, and bug fixes)
]

# Use custom user model
AUTH_USER_MODEL = "users.CustomUser"
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Load environment variables from .env file
<<<<<<< HEAD
<<<<<<< HEAD
load_dotenv(os.path.join(BASE_DIR, ".env"))
=======
load_dotenv(os.path.join(BASE_DIR, '.env'))
>>>>>>> 453538e (Configure for Heroku deployment with PostgreSQL, Redis, and WhiteNoise)
=======
load_dotenv(os.path.join(BASE_DIR, ".env"))
>>>>>>> 11b5166 (Major feature updates: pagination, live search, admin dashboard, and bug fixes)

# Use environment variable for SECRET_KEY
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "unsafe-dev-key-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 11b5166 (Major feature updates: pagination, live search, admin dashboard, and bug fixes)
ALLOWED_HOSTS = os.environ.get(
    "DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,[::1]"
).split(",")
=======
# Allow hosts configuration
ALLOWED_HOSTS = [
    "healthcare-saas-app-83507e23ea58.herokuapp.com",
    "localhost",
    "127.0.0.1",
    "[::1]",
]
>>>>>>> eab6610 (Update Login component and other changes)

# Site URL for emails and absolute URLs
SITE_URL = os.environ.get("SITE_URL", "http://localhost:8000")
<<<<<<< HEAD
=======
ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,[::1]").split(",")
>>>>>>> 453538e (Configure for Heroku deployment with PostgreSQL, Redis, and WhiteNoise)
=======
>>>>>>> 11b5166 (Major feature updates: pagination, live search, admin dashboard, and bug fixes)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
<<<<<<< HEAD
    # REST Framework & JWT
    "rest_framework",
    "corsheaders",
    "drf_spectacular",
=======
>>>>>>> 453538e (Configure for Heroku deployment with PostgreSQL, Redis, and WhiteNoise)
    # Project apps
    "common",
    "tenants",
    "users",
    "patients",
    "appointments",
    "clinical_records",
    "labs",
    "audit_logs",
    "billing",
    "referrals",
    "documents",
    "analytics",
    "ai",
    "fhir",
<<<<<<< HEAD
<<<<<<< HEAD
    "admin_dashboard",
    "api",
=======
>>>>>>> 453538e (Configure for Heroku deployment with PostgreSQL, Redis, and WhiteNoise)
=======
    "admin_dashboard",
>>>>>>> 11b5166 (Major feature updates: pagination, live search, admin dashboard, and bug fixes)
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Serve static files on Heroku
<<<<<<< HEAD
    "corsheaders.middleware.CorsMiddleware",  # CORS middleware (must be before CommonMiddleware)
=======
>>>>>>> 453538e (Configure for Heroku deployment with PostgreSQL, Redis, and WhiteNoise)
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
<<<<<<< HEAD
<<<<<<< HEAD
                "common.context_processors.recent_patients",
=======
>>>>>>> 453538e (Configure for Heroku deployment with PostgreSQL, Redis, and WhiteNoise)
=======
                "common.context_processors.recent_patients",
>>>>>>> 11b5166 (Major feature updates: pagination, live search, admin dashboard, and bug fixes)
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Default to SQLite for local development, but use PostgreSQL on Heroku
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Enable WhiteNoise's GZip and caching support
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 11b5166 (Major feature updates: pagination, live search, admin dashboard, and bug fixes)
# Media files (User-uploaded content)
# https://docs.djangoproject.com/en/6.0/topics/files/

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

<<<<<<< HEAD
# Stripe configuration
STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "")
STRIPE_PUBLISHABLE_KEY = os.environ.get("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "")
=======
# Stripe configuration
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')
>>>>>>> 453538e (Configure for Heroku deployment with PostgreSQL, Redis, and WhiteNoise)
=======
# Stripe configuration
STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "")
STRIPE_PUBLISHABLE_KEY = os.environ.get("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "")
>>>>>>> 11b5166 (Major feature updates: pagination, live search, admin dashboard, and bug fixes)

# SECURITY WARNING: keep the secret key used in production secret!
# Additional security best practices for production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
<<<<<<< HEAD

# ============================================
# REST Framework Configuration
# ============================================
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_FILTER_BACKENDS": [
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "1000/hour",
    },
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
}

# JWT Configuration

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
}

# CORS Configuration - Allow frontend to access API
CORS_ALLOWED_ORIGINS = os.environ.get(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:5173"
).split(",")

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# DRF Spectacular (API Documentation)
SPECTACULAR_SETTINGS = {
    "TITLE": "ClinicCloud API",
    "DESCRIPTION": "Healthcare SaaS Platform API",
    "VERSION": "1.0.0",
    "SERVE_PERMISSIONS": ["rest_framework.permissions.IsAuthenticated"],
    "SERVE_AUTHENTICATION": ["rest_framework_simplejwt.authentication.JWTAuthentication"],
}

SECURE_HSTS_SECONDS = 3600
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
<<<<<<< HEAD
=======
    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
>>>>>>> 453538e (Configure for Heroku deployment with PostgreSQL, Redis, and WhiteNoise)
=======

CORS_ALLOW_ALL_ORIGINS = True  # For development only; restrict in production
>>>>>>> eab6610 (Update Login component and other changes)
